name: "Test set toggle parameter value (V2) task"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
jobs:
  test_rollout_v2_job:
    runs-on: ubuntu-latest
    name: Rollout test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: esquio-set-parameter-v2
        uses: ./
        with:
          esquioUrl: 'https://esquiodemoui.azurewebsites.net/'
          esquioApiKey: ${{ secrets.apikey }}
          productName: 'Default'
          featureName: 'DarkMode'
          toggleType: 'Esquio.Toggles.GradualRolloutUserNameToggle,Esquio'
          parameterName: 'Percentage'
          value: '59'
